# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_store',
            name='cat',
            field=models.CharField(max_length=200),
        ),
    ]
