# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
